name: ci-golang-workflow
on: [push]
jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.2.0
      - run: go test
      - run: go run math.go